#!/usr/bin/env python3
"""Generate per-language .po files and compile .mo into the package.

Run from the repo root:  python3 po/generate.py
Re-run after `xgettext` updates po/claude-session-manager.pot with new strings;
fill any new msgids in TRANSLATIONS below (missing ones fall back to English).
"""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALE = ROOT / "claude_session_manager" / "locale"
DOMAIN = "claude-session-manager"

TRANSLATIONS: dict[str, dict[str, str]] = {
    "hu": {
        "Rename session": "Munkamenet átnevezése",
        "Custom name": "Egyéni név",
        "Cancel": "Mégse",
        "Save": "Mentés",
        "Set tab emoji": "Lap emodzsi beállítása",
        "Shown before the tab title. Leave empty to remove.":
            "A lap címe előtt jelenik meg. Hagyd üresen az eltávolításhoz.",
        "e.g. 🚀": "pl. 🚀",
        "OK": "OK",
        "No MCP servers configured": "Nincs konfigurált MCP-kiszolgáló",
        "Global": "Globális",
        "Available to every project": "Minden projekthez elérhető",
        "MCP Servers": "MCP-kiszolgálók",
        "Read-only": "Csak olvasható",
        "Reading transcript…": "Átirat olvasása…",
        "Session details": "Munkamenet részletei",
        "Session ID": "Munkamenet-azonosító",
        "Directory": "Könyvtár",
        "unknown": "ismeretlen",
        "Created": "Létrehozva",
        "Last activity": "Utolsó tevékenység",
        "Messages": "Üzenetek",
        "Tool calls": "Eszközhívások",
        "Models": "Modellek",
        "Tokens": "Tokenek",
        "Transcript size": "Átirat mérete",
        "MCP": "MCP",
        "Available to this project": "Ehhez a projekthez elérhető",
        "Tools used in this session": "A munkamenetben használt eszközök",
        "Recent activity": "Legutóbbi tevékenység",
        "You": "Te",
        "Claude": "Claude",
        "Follow system": "Rendszer követése",
        "Light": "Világos",
        "Dark": "Sötét",
        "Preferences": "Beállítások",
        "General": "Általános",
        "Terminal": "Terminál",
        "Font": "Betűtípus",
        "Applies to all terminal tabs": "Minden terminállapra érvényes",
        "Reset to default font": "Visszaállítás az alapértelmezett betűtípusra",
        "Scrollback lines": "Visszagörgetési sorok",
        "Color theme": "Színtéma",
        "Appearance": "Megjelenés",
        "Color scheme": "Színséma",
        "Language": "Nyelv",
        "Restart to apply": "Újraindítás szükséges",
        "Notifications": "Értesítések",
        "Notify when a session goes idle": "Értesítés, ha egy munkamenet tétlenné válik",
        "Desktop notification when a background tab stops producing output":
            "Asztali értesítés, amikor egy háttérlap abbahagyja a kimenet előállítását",
        "Claude is waiting for your reply": "A Claude a válaszodra vár",
        "Remove from favorites": "Eltávolítás a kedvencekből",
        "Add to favorites": "Hozzáadás a kedvencekhez",
        "Sessions": "Munkamenetek",
        "Select sessions": "Munkamenetek kijelölése",
        "Show hidden sessions": "Rejtett munkamenetek megjelenítése",
        "MCP servers": "MCP-kiszolgálók",
        "About Claude Session Manager": "A Claude Session Manager névjegye",
        "Refresh session list": "Munkamenetlista frissítése",
        "Search sessions…": "Munkamenetek keresése…",
        "Collapse all groups": "Összes csoport összecsukása",
        "Expand all groups": "Összes csoport kibontása",
        "No sessions found": "Nincs találat",
        "{n} sessions": "{n} munkamenet",
        "{n} projects": "{n} projekt",
        "{n} open": "{n} megnyitva",
        "Favorites": "Kedvencek",
        "Open": "Megnyitás",
        "Open in Ghostty": "Megnyitás Ghosttyban",
        "Fork session": "Munkamenet elágaztatása",
        "Rename…": "Átnevezés…",
        "Details…": "Részletek…",
        "Copy session ID": "Munkamenet-azonosító másolása",
        "Export as Markdown…": "Exportálás Markdownként…",
        "Reveal transcript": "Átirat megjelenítése",
        "Unhide session": "Munkamenet felfedése",
        "Hide session": "Munkamenet elrejtése",
        "Move transcript to trash…": "Átirat kukába helyezése…",
        "All": "Mind",
        "Select all (filtered) sessions": "Az összes (szűrt) munkamenet kijelölése",
        "None": "Egyik sem",
        "Clear selection": "Kijelölés törlése",
        "Move selected transcripts to trash…": "Kijelölt átiratok kukába helyezése…",
        "Hide selected": "Kijelöltek elrejtése",
        "Remove selected from favorites": "Kijelöltek eltávolítása a kedvencekből",
        "Add selected to favorites": "Kijelöltek hozzáadása a kedvencekhez",
        "Open selected in tabs": "Kijelöltek megnyitása lapokon",
        "warning: project dir {cwd} no longer exists, starting in HOME":
            "figyelmeztetés: a(z) {cwd} projektkönyvtár már nem létezik, indítás a HOME-ban",
        "warning: `claude` not found in PATH — starting a plain shell":
            "figyelmeztetés: a `claude` nem található a PATH-ban — egyszerű parancsértelmező indítása",
        "failed to start shell: {msg}": "nem sikerült elindítani a parancsértelmezőt: {msg}",
        "Find in terminal…": "Keresés a terminálban…",
        "Previous match": "Előző találat",
        "Next match": "Következő találat",
        "Set emoji…": "Emodzsi beállítása…",
        "Close": "Bezárás",
        "Toggle sidebar (F9)": "Oldalsáv ki/be (F9)",
        "New session in folder…": "Új munkamenet mappában…",
        "New Claude session (Ctrl+Shift+T)": "Új Claude-munkamenet (Ctrl+Shift+T)",
        "Close all tabs": "Összes lap bezárása",
        "No session open": "Nincs megnyitott munkamenet",
        "Pick a session from the sidebar, or start a new one.":
            "Válassz egy munkamenetet az oldalsávból, vagy indíts egy újat.",
        "Some transcripts could not be trashed": "Néhány átiratot nem sikerült a kukába helyezni",
        "Move {n} transcript(s) to trash?": "{n} átirat kukába helyezése?",
        "The files are moved to the trash and can be restored.":
            "A fájlok a kukába kerülnek, és visszaállíthatók.",
        "Move to Trash": "Kukába",
        "New window": "Új ablak",
        "You interrupted Claude here": "Itt szakítottad meg a Claude-ot",
        "Restart now": "Újraindítás most",
        "Choose project directory": "Válassz projektkönyvtárat",
        "Tab name": "Lap neve",
        "Export session as Markdown": "Munkamenet exportálása Markdownként",
        "Export failed": "Az exportálás sikertelen",
        "Could not trash transcript": "Az átiratot nem sikerült a kukába helyezni",
        "Move transcript to trash?": "Átirat kukába helyezése?",
        "“{name}” will be removed from Claude's history.":
            "A(z) „{name}” eltávolításra kerül a Claude előzményeiből.",
        "The file is moved to the trash and can be restored.":
            "A fájl a kukába kerül, és visszaállítható.",
    },
    "de": {
        "Rename session": "Sitzung umbenennen",
        "Custom name": "Eigener Name",
        "Cancel": "Abbrechen",
        "Save": "Speichern",
        "Set tab emoji": "Tab-Emoji festlegen",
        "Shown before the tab title. Leave empty to remove.":
            "Wird vor dem Tab-Titel angezeigt. Zum Entfernen leer lassen.",
        "e.g. 🚀": "z. B. 🚀",
        "OK": "OK",
        "No MCP servers configured": "Keine MCP-Server konfiguriert",
        "Global": "Global",
        "Available to every project": "Für jedes Projekt verfügbar",
        "MCP Servers": "MCP-Server",
        "Read-only": "Schreibgeschützt",
        "Reading transcript…": "Transkript wird gelesen…",
        "Session details": "Sitzungsdetails",
        "Session ID": "Sitzungs-ID",
        "Directory": "Verzeichnis",
        "unknown": "unbekannt",
        "Created": "Erstellt",
        "Last activity": "Letzte Aktivität",
        "Messages": "Nachrichten",
        "Tool calls": "Tool-Aufrufe",
        "Models": "Modelle",
        "Tokens": "Tokens",
        "Transcript size": "Transkriptgröße",
        "MCP": "MCP",
        "Available to this project": "Für dieses Projekt verfügbar",
        "Tools used in this session": "In dieser Sitzung verwendete Tools",
        "Recent activity": "Letzte Aktivität",
        "You": "Du",
        "Claude": "Claude",
        "Follow system": "System folgen",
        "Light": "Hell",
        "Dark": "Dunkel",
        "Preferences": "Einstellungen",
        "General": "Allgemein",
        "Terminal": "Terminal",
        "Font": "Schriftart",
        "Applies to all terminal tabs": "Gilt für alle Terminal-Tabs",
        "Reset to default font": "Auf Standardschriftart zurücksetzen",
        "Scrollback lines": "Scrollback-Zeilen",
        "Color theme": "Farbthema",
        "Appearance": "Erscheinungsbild",
        "Color scheme": "Farbschema",
        "Language": "Sprache",
        "Restart to apply": "Neustart erforderlich",
        "Notifications": "Benachrichtigungen",
        "Notify when a session goes idle": "Benachrichtigen, wenn eine Sitzung untätig wird",
        "Desktop notification when a background tab stops producing output":
            "Desktop-Benachrichtigung, wenn ein Hintergrund-Tab keine Ausgabe mehr erzeugt",
        "Claude is waiting for your reply": "Claude wartet auf deine Antwort",
        "Remove from favorites": "Aus Favoriten entfernen",
        "Add to favorites": "Zu Favoriten hinzufügen",
        "Sessions": "Sitzungen",
        "Select sessions": "Sitzungen auswählen",
        "Show hidden sessions": "Versteckte Sitzungen anzeigen",
        "MCP servers": "MCP-Server",
        "About Claude Session Manager": "Über Claude Session Manager",
        "Refresh session list": "Sitzungsliste aktualisieren",
        "Search sessions…": "Sitzungen suchen…",
        "Collapse all groups": "Alle Gruppen einklappen",
        "Expand all groups": "Alle Gruppen ausklappen",
        "No sessions found": "Keine Sitzungen gefunden",
        "{n} sessions": "{n} Sitzungen",
        "{n} projects": "{n} Projekte",
        "{n} open": "{n} geöffnet",
        "Favorites": "Favoriten",
        "Open": "Öffnen",
        "Open in Ghostty": "In Ghostty öffnen",
        "Fork session": "Sitzung verzweigen",
        "Rename…": "Umbenennen…",
        "Details…": "Details…",
        "Copy session ID": "Sitzungs-ID kopieren",
        "Export as Markdown…": "Als Markdown exportieren…",
        "Reveal transcript": "Transkript anzeigen",
        "Unhide session": "Sitzung einblenden",
        "Hide session": "Sitzung ausblenden",
        "Move transcript to trash…": "Transkript in den Papierkorb verschieben…",
        "All": "Alle",
        "Select all (filtered) sessions": "Alle (gefilterten) Sitzungen auswählen",
        "None": "Keine",
        "Clear selection": "Auswahl aufheben",
        "Move selected transcripts to trash…":
            "Ausgewählte Transkripte in den Papierkorb verschieben…",
        "Hide selected": "Ausgewählte ausblenden",
        "Remove selected from favorites": "Ausgewählte aus Favoriten entfernen",
        "Add selected to favorites": "Ausgewählte zu Favoriten hinzufügen",
        "Open selected in tabs": "Ausgewählte in Tabs öffnen",
        "warning: project dir {cwd} no longer exists, starting in HOME":
            "Warnung: Projektverzeichnis {cwd} existiert nicht mehr, starte im HOME",
        "warning: `claude` not found in PATH — starting a plain shell":
            "Warnung: `claude` nicht im PATH gefunden — starte eine einfache Shell",
        "failed to start shell: {msg}": "Shell konnte nicht gestartet werden: {msg}",
        "Find in terminal…": "Im Terminal suchen…",
        "Previous match": "Vorheriger Treffer",
        "Next match": "Nächster Treffer",
        "Set emoji…": "Emoji festlegen…",
        "Close": "Schließen",
        "Toggle sidebar (F9)": "Seitenleiste umschalten (F9)",
        "New session in folder…": "Neue Sitzung im Ordner…",
        "New Claude session (Ctrl+Shift+T)": "Neue Claude-Sitzung (Strg+Umschalt+T)",
        "Close all tabs": "Alle Tabs schließen",
        "No session open": "Keine Sitzung geöffnet",
        "Pick a session from the sidebar, or start a new one.":
            "Wähle eine Sitzung in der Seitenleiste oder starte eine neue.",
        "Some transcripts could not be trashed":
            "Einige Transkripte konnten nicht in den Papierkorb verschoben werden",
        "Move {n} transcript(s) to trash?": "{n} Transkript(e) in den Papierkorb verschieben?",
        "The files are moved to the trash and can be restored.":
            "Die Dateien werden in den Papierkorb verschoben und können wiederhergestellt werden.",
        "Move to Trash": "In den Papierkorb",
        "New window": "Neues Fenster",
        "You interrupted Claude here": "Du hast Claude hier unterbrochen",
        "Restart now": "Jetzt neu starten",
        "Choose project directory": "Projektverzeichnis wählen",
        "Tab name": "Tab-Name",
        "Export session as Markdown": "Sitzung als Markdown exportieren",
        "Export failed": "Export fehlgeschlagen",
        "Could not trash transcript":
            "Transkript konnte nicht in den Papierkorb verschoben werden",
        "Move transcript to trash?": "Transkript in den Papierkorb verschieben?",
        "“{name}” will be removed from Claude's history.":
            "„{name}“ wird aus Claudes Verlauf entfernt.",
        "The file is moved to the trash and can be restored.":
            "Die Datei wird in den Papierkorb verschoben und kann wiederhergestellt werden.",
    },
    "es": {
        "Rename session": "Renombrar sesión",
        "Custom name": "Nombre personalizado",
        "Cancel": "Cancelar",
        "Save": "Guardar",
        "Set tab emoji": "Establecer emoji de pestaña",
        "Shown before the tab title. Leave empty to remove.":
            "Se muestra antes del título de la pestaña. Déjalo vacío para quitarlo.",
        "e.g. 🚀": "p. ej. 🚀",
        "OK": "Aceptar",
        "No MCP servers configured": "No hay servidores MCP configurados",
        "Global": "Global",
        "Available to every project": "Disponible para todos los proyectos",
        "MCP Servers": "Servidores MCP",
        "Read-only": "Solo lectura",
        "Reading transcript…": "Leyendo transcripción…",
        "Session details": "Detalles de la sesión",
        "Session ID": "ID de sesión",
        "Directory": "Directorio",
        "unknown": "desconocido",
        "Created": "Creada",
        "Last activity": "Última actividad",
        "Messages": "Mensajes",
        "Tool calls": "Llamadas a herramientas",
        "Models": "Modelos",
        "Tokens": "Tokens",
        "Transcript size": "Tamaño de la transcripción",
        "MCP": "MCP",
        "Available to this project": "Disponible para este proyecto",
        "Tools used in this session": "Herramientas usadas en esta sesión",
        "Recent activity": "Actividad reciente",
        "You": "Tú",
        "Claude": "Claude",
        "Follow system": "Seguir el sistema",
        "Light": "Claro",
        "Dark": "Oscuro",
        "Preferences": "Preferencias",
        "General": "General",
        "Terminal": "Terminal",
        "Font": "Fuente",
        "Applies to all terminal tabs": "Se aplica a todas las pestañas de terminal",
        "Reset to default font": "Restablecer la fuente predeterminada",
        "Scrollback lines": "Líneas de historial",
        "Color theme": "Tema de color",
        "Appearance": "Apariencia",
        "Color scheme": "Esquema de color",
        "Language": "Idioma",
        "Restart to apply": "Reinicia para aplicar",
        "Notifications": "Notificaciones",
        "Notify when a session goes idle": "Notificar cuando una sesión quede inactiva",
        "Desktop notification when a background tab stops producing output":
            "Notificación de escritorio cuando una pestaña en segundo plano deja de producir salida",
        "Claude is waiting for your reply": "Claude está esperando tu respuesta",
        "Remove from favorites": "Quitar de favoritos",
        "Add to favorites": "Añadir a favoritos",
        "Sessions": "Sesiones",
        "Select sessions": "Seleccionar sesiones",
        "Show hidden sessions": "Mostrar sesiones ocultas",
        "MCP servers": "Servidores MCP",
        "About Claude Session Manager": "Acerca de Claude Session Manager",
        "Refresh session list": "Actualizar la lista de sesiones",
        "Search sessions…": "Buscar sesiones…",
        "Collapse all groups": "Contraer todos los grupos",
        "Expand all groups": "Expandir todos los grupos",
        "No sessions found": "No se encontraron sesiones",
        "{n} sessions": "{n} sesiones",
        "{n} projects": "{n} proyectos",
        "{n} open": "{n} abiertas",
        "Favorites": "Favoritos",
        "Open": "Abrir",
        "Open in Ghostty": "Abrir en Ghostty",
        "Fork session": "Bifurcar sesión",
        "Rename…": "Renombrar…",
        "Details…": "Detalles…",
        "Copy session ID": "Copiar ID de sesión",
        "Export as Markdown…": "Exportar como Markdown…",
        "Reveal transcript": "Mostrar transcripción",
        "Unhide session": "Mostrar sesión",
        "Hide session": "Ocultar sesión",
        "Move transcript to trash…": "Mover transcripción a la papelera…",
        "All": "Todas",
        "Select all (filtered) sessions": "Seleccionar todas las sesiones (filtradas)",
        "None": "Ninguna",
        "Clear selection": "Borrar selección",
        "Move selected transcripts to trash…":
            "Mover las transcripciones seleccionadas a la papelera…",
        "Hide selected": "Ocultar seleccionadas",
        "Remove selected from favorites": "Quitar seleccionadas de favoritos",
        "Add selected to favorites": "Añadir seleccionadas a favoritos",
        "Open selected in tabs": "Abrir seleccionadas en pestañas",
        "warning: project dir {cwd} no longer exists, starting in HOME":
            "advertencia: el directorio del proyecto {cwd} ya no existe, iniciando en HOME",
        "warning: `claude` not found in PATH — starting a plain shell":
            "advertencia: no se encontró `claude` en PATH — iniciando una shell simple",
        "failed to start shell: {msg}": "no se pudo iniciar la shell: {msg}",
        "Find in terminal…": "Buscar en la terminal…",
        "Previous match": "Coincidencia anterior",
        "Next match": "Coincidencia siguiente",
        "Set emoji…": "Establecer emoji…",
        "Close": "Cerrar",
        "Toggle sidebar (F9)": "Mostrar u ocultar la barra lateral (F9)",
        "New session in folder…": "Nueva sesión en carpeta…",
        "New Claude session (Ctrl+Shift+T)": "Nueva sesión de Claude (Ctrl+Mayús+T)",
        "Close all tabs": "Cerrar todas las pestañas",
        "No session open": "Ninguna sesión abierta",
        "Pick a session from the sidebar, or start a new one.":
            "Elige una sesión en la barra lateral o inicia una nueva.",
        "Some transcripts could not be trashed":
            "No se pudieron enviar a la papelera algunas transcripciones",
        "Move {n} transcript(s) to trash?": "¿Mover {n} transcripción(es) a la papelera?",
        "The files are moved to the trash and can be restored.":
            "Los archivos se mueven a la papelera y se pueden restaurar.",
        "Move to Trash": "Mover a la papelera",
        "New window": "Nueva ventana",
        "You interrupted Claude here": "Interrumpiste a Claude aquí",
        "Restart now": "Reiniciar ahora",
        "Choose project directory": "Elegir directorio del proyecto",
        "Tab name": "Nombre de la pestaña",
        "Export session as Markdown": "Exportar sesión como Markdown",
        "Export failed": "Error al exportar",
        "Could not trash transcript": "No se pudo enviar la transcripción a la papelera",
        "Move transcript to trash?": "¿Mover la transcripción a la papelera?",
        "“{name}” will be removed from Claude's history.":
            "«{name}» se eliminará del historial de Claude.",
        "The file is moved to the trash and can be restored.":
            "El archivo se mueve a la papelera y se puede restaurar.",
    },
    "fr": {
        "Rename session": "Renommer la session",
        "Custom name": "Nom personnalisé",
        "Cancel": "Annuler",
        "Save": "Enregistrer",
        "Set tab emoji": "Définir l’emoji de l’onglet",
        "Shown before the tab title. Leave empty to remove.":
            "Affiché avant le titre de l’onglet. Laisser vide pour le retirer.",
        "e.g. 🚀": "p. ex. 🚀",
        "OK": "OK",
        "No MCP servers configured": "Aucun serveur MCP configuré",
        "Global": "Global",
        "Available to every project": "Disponible pour tous les projets",
        "MCP Servers": "Serveurs MCP",
        "Read-only": "Lecture seule",
        "Reading transcript…": "Lecture de la transcription…",
        "Session details": "Détails de la session",
        "Session ID": "ID de session",
        "Directory": "Répertoire",
        "unknown": "inconnu",
        "Created": "Créée",
        "Last activity": "Dernière activité",
        "Messages": "Messages",
        "Tool calls": "Appels d’outils",
        "Models": "Modèles",
        "Tokens": "Jetons",
        "Transcript size": "Taille de la transcription",
        "MCP": "MCP",
        "Available to this project": "Disponible pour ce projet",
        "Tools used in this session": "Outils utilisés dans cette session",
        "Recent activity": "Activité récente",
        "You": "Vous",
        "Claude": "Claude",
        "Follow system": "Suivre le système",
        "Light": "Clair",
        "Dark": "Sombre",
        "Preferences": "Préférences",
        "General": "Général",
        "Terminal": "Terminal",
        "Font": "Police",
        "Applies to all terminal tabs": "S’applique à tous les onglets de terminal",
        "Reset to default font": "Réinitialiser la police par défaut",
        "Scrollback lines": "Lignes d’historique",
        "Color theme": "Thème de couleurs",
        "Appearance": "Apparence",
        "Color scheme": "Schéma de couleurs",
        "Language": "Langue",
        "Restart to apply": "Redémarrer pour appliquer",
        "Notifications": "Notifications",
        "Notify when a session goes idle": "Notifier lorsqu’une session devient inactive",
        "Desktop notification when a background tab stops producing output":
            "Notification de bureau lorsqu’un onglet en arrière-plan cesse de produire une sortie",
        "Claude is waiting for your reply": "Claude attend votre réponse",
        "Remove from favorites": "Retirer des favoris",
        "Add to favorites": "Ajouter aux favoris",
        "Sessions": "Sessions",
        "Select sessions": "Sélectionner des sessions",
        "Show hidden sessions": "Afficher les sessions masquées",
        "MCP servers": "Serveurs MCP",
        "About Claude Session Manager": "À propos de Claude Session Manager",
        "Refresh session list": "Actualiser la liste des sessions",
        "Search sessions…": "Rechercher des sessions…",
        "Collapse all groups": "Réduire tous les groupes",
        "Expand all groups": "Développer tous les groupes",
        "No sessions found": "Aucune session trouvée",
        "{n} sessions": "{n} sessions",
        "{n} projects": "{n} projets",
        "{n} open": "{n} ouvertes",
        "Favorites": "Favoris",
        "Open": "Ouvrir",
        "Open in Ghostty": "Ouvrir dans Ghostty",
        "Fork session": "Bifurquer la session",
        "Rename…": "Renommer…",
        "Details…": "Détails…",
        "Copy session ID": "Copier l’ID de session",
        "Export as Markdown…": "Exporter en Markdown…",
        "Reveal transcript": "Afficher la transcription",
        "Unhide session": "Afficher la session",
        "Hide session": "Masquer la session",
        "Move transcript to trash…": "Mettre la transcription à la corbeille…",
        "All": "Tout",
        "Select all (filtered) sessions": "Sélectionner toutes les sessions (filtrées)",
        "None": "Aucune",
        "Clear selection": "Effacer la sélection",
        "Move selected transcripts to trash…":
            "Mettre les transcriptions sélectionnées à la corbeille…",
        "Hide selected": "Masquer la sélection",
        "Remove selected from favorites": "Retirer la sélection des favoris",
        "Add selected to favorites": "Ajouter la sélection aux favoris",
        "Open selected in tabs": "Ouvrir la sélection dans des onglets",
        "warning: project dir {cwd} no longer exists, starting in HOME":
            "avertissement : le répertoire de projet {cwd} n’existe plus, démarrage dans HOME",
        "warning: `claude` not found in PATH — starting a plain shell":
            "avertissement : `claude` introuvable dans le PATH — démarrage d’un shell simple",
        "failed to start shell: {msg}": "échec du démarrage du shell : {msg}",
        "Find in terminal…": "Rechercher dans le terminal…",
        "Previous match": "Correspondance précédente",
        "Next match": "Correspondance suivante",
        "Set emoji…": "Définir un emoji…",
        "Close": "Fermer",
        "Toggle sidebar (F9)": "Afficher/masquer la barre latérale (F9)",
        "New session in folder…": "Nouvelle session dans le dossier…",
        "New Claude session (Ctrl+Shift+T)": "Nouvelle session Claude (Ctrl+Maj+T)",
        "Close all tabs": "Fermer tous les onglets",
        "No session open": "Aucune session ouverte",
        "Pick a session from the sidebar, or start a new one.":
            "Choisissez une session dans la barre latérale, ou démarrez-en une nouvelle.",
        "Some transcripts could not be trashed":
            "Certaines transcriptions n’ont pas pu être mises à la corbeille",
        "Move {n} transcript(s) to trash?": "Mettre {n} transcription(s) à la corbeille ?",
        "The files are moved to the trash and can be restored.":
            "Les fichiers sont mis à la corbeille et peuvent être restaurés.",
        "Move to Trash": "Mettre à la corbeille",
        "New window": "Nouvelle fenêtre",
        "You interrupted Claude here": "Vous avez interrompu Claude ici",
        "Restart now": "Redémarrer maintenant",
        "Choose project directory": "Choisir le répertoire du projet",
        "Tab name": "Nom de l’onglet",
        "Export session as Markdown": "Exporter la session en Markdown",
        "Export failed": "Échec de l’exportation",
        "Could not trash transcript": "Impossible de mettre la transcription à la corbeille",
        "Move transcript to trash?": "Mettre la transcription à la corbeille ?",
        "“{name}” will be removed from Claude's history.":
            "« {name} » sera retiré de l’historique de Claude.",
        "The file is moved to the trash and can be restored.":
            "Le fichier est mis à la corbeille et peut être restauré.",
    },
}

_HEADER = (
    'msgid ""\n'
    'msgstr ""\n'
    '"Project-Id-Version: claude-session-manager\\n"\n'
    '"Language: {lang}\\n"\n'
    '"MIME-Version: 1.0\\n"\n'
    '"Content-Type: text/plain; charset=UTF-8\\n"\n'
    '"Content-Transfer-Encoding: 8bit\\n"\n'
    '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n\n'
)


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    for lang, entries in TRANSLATIONS.items():
        po_path = Path(__file__).resolve().parent / f"{lang}.po"
        body = [_HEADER.format(lang=lang)]
        for msgid, msgstr in entries.items():
            body.append(f'msgid "{_escape(msgid)}"\n')
            body.append(f'msgstr "{_escape(msgstr)}"\n\n')
        po_path.write_text("".join(body), encoding="utf-8")

        mo_dir = LOCALE / lang / "LC_MESSAGES"
        mo_dir.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["msgfmt", "-o", str(mo_dir / f"{DOMAIN}.mo"), str(po_path)], check=True
        )
        print(f"{lang}: {len(entries)} strings → {po_path.name} + .mo")


if __name__ == "__main__":
    main()
